### ISSUE TITLE
Cannot compile on Ubuntu 23.10 (yaml.h: No such file or directory)

### ISSUE THREAD

**Issue by ghost** [ayyi/samplecat#68]
I'm trying to compile this on Ubuntu 23.10. When running `make` it gets far and then fails with the following error:

```
In file included from gdl-dock-layout.c:42:
../../lib/yaml/load.h:16:10: fatal error: yaml.h: No such file or directory
   16 | #include <yaml.h>
```

**Comment by ayyi** [comment]
Hi, I believe the problem will be fixed if you install `libyaml-dev`.

I have improved the configure script so that it fails if this package is not found, and added a compilation test for ubuntu 23.

Thanks for reporting the issue. Please shout if the above does not fix it for you.
